# Dockerfile for Gunicorn/Flask app container

# Use Python 3.10 as Docker base image
FROM python:3.10-slim

# Install PostgreSQL dependencies
RUN apt-get update \
    && apt-get install -y libpq-dev gcc

WORKDIR /app

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app.py to container
COPY . .

EXPOSE 5000

ENV FLASK_APP=app.py
ENV PYTHONDONTWRITEBYTECODE 1

# Use Gunicorn server to run Flask app
CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:5000"]